version: '2'

services:
  nginx:
    image: dang3r/nginx-redirect:latest
    restart: always
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      TARGET_URL: ${TARGET_URL}
    volumes:
      - /etc/ssl/ssl.cert:/etc/ssl/ssl.cert:ro
      - /etc/ssl/ssl.key:/etc/ssl/ssl.key:ro
    ports:
      - "80:80"
      - "443:443"
